### ISSUE TITLE
public gateway is not available

### ISSUE THREAD

**Issue by codeninja819** [warengonzaga/ipfs-support-extension#7]
Thirdweb public gateway is not available without API key from [Aug 1st, 2023](https://blog.thirdweb.com/changelog/api-keys-to-access-thirdweb-infra).
We can use another gateways. And it would be great if we add options to select one of public gateways, and add feature to add custom gateway.

**Comment by warengonzaga** [comment]
Hello @codeninja819 I'm so sorry about this, I'll find some time to update the public gateway.

**Comment by warengonzaga** [comment]
Hello @codeninja819 kindly check the releases tab and download the latest version of it with the fix. I almost forgot to release the 0.1.1 of the extension which contains the fix. I submitted an updated version to the chrome web store, awaiting their approval.

**Comment by warengonzaga** [comment]
This is a duplicate of my recent issue #4

**Comment by warengonzaga** [comment]
The latest version has been published.
https://chromewebstore.google.com/detail/bgkgpjkailocmhjioiakogohkahhfbhp

**Comment by codeninja819** [comment]
Thanks @warengonzaga.
I liked the update.

**Comment by warengonzaga** [comment]
> Thanks @warengonzaga. I liked the update.

No worries, thank you for your support I really appreciate it!
