### ISSUE TITLE
add support to arweave

### ISSUE THREAD

**Issue by codeninja819** [warengonzaga/ipfs-support-extension#8]
It would be nice to add support to [Arweave](https://www.arweave.org).
ar://jK9sR4OrYvODj7PD3czIAyNJalub0-vdV_JAg1NqQ-o &rarr; https://arweave.net/jK9sR4OrYvODj7PD3czIAyNJalub0-vdV_JAg1NqQ-o

**Comment by warengonzaga** [comment]
Hey @codeninja819 that's a good idea, yeah we can do that.

**Comment by warengonzaga** [comment]
I'll find some time to add this and the existing issues. Thanks for the suggestions.

**Comment by warengonzaga** [comment]
Hey @codeninja819 I decided to create a different extension for arweave. I'll let you know here once the extension is approved by the Chrome webstore. Thank you for your support I appreciate it!

**Comment by warengonzaga** [comment]
Hey @codeninja819 here's the latest repo https://github.com/warengonzaga/arweave-support-extension
Keep in mind that this is still under development. Need to polish things before submitting it to Google Chrome Webstore. You can star the repo to follow the dev updates.

**Comment by warengonzaga** [comment]
Hey @codeninja819 the arweave is currently under review on google chrome. Waiting for their approval.

**Comment by codeninja819** [comment]
That sounds good. Thanks.

**Comment by warengonzaga** [comment]
> That sounds good. Thanks.

Update: it is now available on google chrome.
Here's the download link: https://chromewebstore.google.com/detail/arweave-support/ogohioihekalbamphccjangcldbemhgi

Appreciate the support!
